name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ${{ secrets.TARGET_DIRECTORY }}
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm build
            pm2 restart homepage
